CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS laboratories (id text PRIMARY KEY, code text NOT NULL UNIQUE, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS instruments (id text PRIMARY KEY, asset_number text NOT NULL UNIQUE, laboratory_id text NOT NULL REFERENCES laboratories(id), status text NOT NULL, criticality text NOT NULL, next_due_at timestamptz, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS instruments_status_due_idx ON instruments(status,next_due_at);
CREATE TABLE IF NOT EXISTS calibration_items (id text PRIMARY KEY, code text NOT NULL UNIQUE, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS calibration_plans (id text PRIMARY KEY, instrument_id text NOT NULL REFERENCES instruments(id), item_id text NOT NULL REFERENCES calibration_items(id), status text NOT NULL, due_at timestamptz NOT NULL, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS plans_open_unique ON calibration_plans(instrument_id,item_id) WHERE status NOT IN ('completed','cancelled');
CREATE TABLE IF NOT EXISTS calibration_executions (id text PRIMARY KEY, root_id text NOT NULL, instrument_id text NOT NULL REFERENCES instruments(id), item_id text NOT NULL REFERENCES calibration_items(id), conclusion text NOT NULL, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS executions_root_idx ON calibration_executions(root_id,created_at);
CREATE TABLE IF NOT EXISTS calibration_execution_heads (root_id text PRIMARY KEY, head_id text NOT NULL REFERENCES calibration_executions(id));
CREATE TABLE IF NOT EXISTS nonconformances (id text PRIMARY KEY, instrument_id text NOT NULL REFERENCES instruments(id), status text NOT NULL, version bigint NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS nonconformances_open_unique ON nonconformances(instrument_id) WHERE status <> 'closed';
CREATE TABLE IF NOT EXISTS certificates (id text PRIMARY KEY, number text NOT NULL UNIQUE, instrument_id text NOT NULL REFERENCES instruments(id), expires_at timestamptz NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS certificates_expiry_idx ON certificates(expires_at);
CREATE TABLE IF NOT EXISTS alerts (id text PRIMARY KEY, deduplication_key text NOT NULL UNIQUE, acknowledged_at timestamptz, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id text PRIMARY KEY, entity_type text NOT NULL, entity_id text NOT NULL, created_at timestamptz NOT NULL, data jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS audit_entity_idx ON audit_events(entity_type,entity_id,created_at);
CREATE TABLE IF NOT EXISTS usage_checks (id text PRIMARY KEY, instrument_id text NOT NULL REFERENCES instruments(id), decision text NOT NULL, checked_at timestamptz NOT NULL, data jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS usage_instrument_idx ON usage_checks(instrument_id,checked_at);
CREATE TABLE IF NOT EXISTS idempotency_keys (key text PRIMARY KEY, fingerprint text NOT NULL, completed boolean NOT NULL DEFAULT false, expires_at timestamptz NOT NULL);
